package msc.pizza4you.gui.components;

import java.util.ArrayList;
import msc.pizza4you.gui.listeners.FlowPanelListener;

/**
 *
 * @author Keshan De Silva
 */
public class FlowControlPanel extends javax.swing.JPanel
{
    public enum ButtonType { START, NEXT, BACK, FINISH };
    
    private boolean backButtonEnabled;
    private boolean nextButtonEnabled;
    private boolean finishButtonEnabled;
    private boolean startButtonEnabled;
    
    private final ArrayList<FlowPanelListener> listenerList;
    
    public FlowControlPanel()
    {
        initComponents();
        listenerList = new ArrayList<>();
    }

    public boolean isBackButtonEnabled()
    {
        return backButtonEnabled;
    }

    public void setBackButtonEnabled(boolean backButtonEnabled)
    {
        this.backButtonEnabled = backButtonEnabled;
        btnBack.setEnabled(backButtonEnabled);
    }

    public boolean isNextButtonEnabled()
    {
        return nextButtonEnabled;
    }

    public void setNextButtonEnabled(boolean nextButtonEnabled)
    {
        this.nextButtonEnabled = nextButtonEnabled;
        btnNext.setEnabled(nextButtonEnabled);
    }

    public boolean isFinishButtonEnabled()
    {
        return finishButtonEnabled;
    }

    public void setFinishButtonEnabled(boolean finishButtonEnabled)
    {
        this.finishButtonEnabled = finishButtonEnabled;
        btnFinish.setEnabled(backButtonEnabled);
    }

    public boolean isStartButtonEnabled()
    {
        return startButtonEnabled;
    }

    public void setStartButtonEnabled(boolean startButtonEnabled)
    {
        this.startButtonEnabled = startButtonEnabled;
        btnStartOver.setEnabled(backButtonEnabled);
    }

    public void setButtonEnabled(ButtonType buttonType, boolean enabled)
    {
        switch (buttonType)
        {
            case START : btnStartOver.setEnabled(enabled); break;
            case BACK : btnBack.setEnabled(enabled); break;
            case NEXT : btnNext.setEnabled(enabled); break;
            case FINISH : btnFinish.setEnabled(enabled); break;
        }
    }
        
    public void addFlowPanelListener(FlowPanelListener listener)
    {
        listenerList.add(listener);
    }
    
    public void removeFlowPanelListener(FlowPanelListener listener)
    {
        listenerList.remove(listener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnStartOver = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 51));

        btnStartOver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStartOver.setText("Start Over");
        btnStartOver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartOverActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setText("Next >");
        btnNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });

        btnFinish.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartOver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinish)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnFinish, btnNext, btnStartOver});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartOver)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(btnFinish))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNext, btnStartOver});

    }// </editor-fold>//GEN-END:initComponents

    private void btnStartOverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartOverActionPerformed
    {//GEN-HEADEREND:event_btnStartOverActionPerformed
        onFlowPanelButtonClicked(ButtonType.START);
    }//GEN-LAST:event_btnStartOverActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        onFlowPanelButtonClicked(ButtonType.BACK);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNextActionPerformed
    {//GEN-HEADEREND:event_btnNextActionPerformed
        onFlowPanelButtonClicked(ButtonType.NEXT);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinishActionPerformed
    {//GEN-HEADEREND:event_btnFinishActionPerformed
        onFlowPanelButtonClicked(ButtonType.FINISH);
    }//GEN-LAST:event_btnFinishActionPerformed

    private void onFlowPanelButtonClicked(ButtonType buttonType)
    {
        for (FlowPanelListener listener : listenerList)
        {
            listener.onFlowPanelButtonClicked(buttonType);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStartOver;
    // End of variables declaration//GEN-END:variables
}
