package msc.pizza4you.gui.components;

import java.awt.Graphics;
import java.awt.Graphics2D;
import msc.pizza4you.data.PizzaModel;

/**
 *
 * @author Keshan De Silva
 */
public class PizzaImagePanel extends javax.swing.JPanel
{
    private PizzaModel pizzaModel;
    
    public PizzaImagePanel(PizzaModel pizzaModel)
    {
        initComponents();
        this.setPizzaModel(pizzaModel);
    }

    public PizzaModel getPizzaModel()
    {
        return pizzaModel;
    }

    public final void setPizzaModel(PizzaModel pizzaModel)
    {
        this.pizzaModel = pizzaModel;
        updatePanelUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainLayerPanel = new javax.swing.JLayeredPane();
        lblImage = new javax.swing.JLabel();
        nameLabel = new msc.pizza4you.gui.components.KeywordLabel();
        certaintyLabel = new msc.pizza4you.gui.components.KeywordLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        mainLayerPanel.setBackground(new java.awt.Color(51, 255, 204));
        mainLayerPanel.setOpaque(true);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/pizza4you/resources/images/Veggie Supreme.jpg"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        mainLayerPanel.add(lblImage);
        lblImage.setBounds(0, 0, 306, 306);

        nameLabel.setBackgroungColor(new java.awt.Color(0, 102, 102));
        mainLayerPanel.add(nameLabel);
        nameLabel.setBounds(10, 10, 240, 31);
        mainLayerPanel.setLayer(nameLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        certaintyLabel.setBackgroungColor(new java.awt.Color(102, 0, 102));
        certaintyLabel.setKeywordText("100%");
        mainLayerPanel.add(certaintyLabel);
        certaintyLabel.setBounds(240, 10, 50, 31);
        mainLayerPanel.setLayer(certaintyLabel, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainLayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainLayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private msc.pizza4you.gui.components.KeywordLabel certaintyLabel;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLayeredPane mainLayerPanel;
    private msc.pizza4you.gui.components.KeywordLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    private void updatePanelUI()
    {
        nameLabel.setKeywordText(pizzaModel.getName());
        certaintyLabel.setKeywordText(pizzaModel.getCertaintyString());
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/msc/pizza4you/resources/images/" + pizzaModel.getName() + ".jpg")));
    }
}
