package msc.pizza4you.gui.panels;

import javax.swing.JPanel;
import msc.pizza4you.data.PizzaConfiguration;
import msc.pizza4you.core.Engine;
import msc.pizza4you.core.FlowEngine;
import msc.pizza4you.core.NLPEngine;

/**
 *
 * @author Keshan De Silva
 */
public class StartPanel extends AbstractPanel
{

    public StartPanel()
    {
        initComponents();
        txtMainText.setText("chicken pizza with cheese");
        updateKeywords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelMain = new javax.swing.JPanel();
        lblMainString = new javax.swing.JLabel();
        txtMainText = new javax.swing.JTextField();
        panelKeywords = new javax.swing.JPanel();

        panelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblMainString.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMainString.setText("I am looking for :");

        txtMainText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMainText.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtMainTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblMainString)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtMainText, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainString)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKeywords.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizza Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelKeywords.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMainTextKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtMainTextKeyReleased
    {//GEN-HEADEREND:event_txtMainTextKeyReleased
//        PizzaConfiguration pizzaConfiguration = null;
//        if (!txtMainText.getText().trim().isEmpty())
//        {
//            pizzaConfiguration = NLPEngine.getInstance().generatePizzaConfiguration(txtMainText.getText());
//        }
//       
        updateKeywords();
    }//GEN-LAST:event_txtMainTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMainString;
    private javax.swing.JPanel panelKeywords;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtMainText;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getPanelTitle()
    {
        return "Start Page";
    }
    
    @Override
    public PizzaConfiguration updatePizzaConfigurations()
    {
        Engine engine = Engine.getInstance();   
        PizzaConfiguration pizzaConfiguration = null;
        
        if (!txtMainText.getText().trim().isEmpty())
        {
            pizzaConfiguration = NLPEngine.getInstance().generatePizzaConfiguration(txtMainText.getText());
            engine.setPizzaConfiguration(pizzaConfiguration);
        }
        
        FlowEngine.getInstance().updateFlow(pizzaConfiguration);

        return pizzaConfiguration;
    }

    @Override
    public JPanel getKeywordPanel()
    {
        return panelKeywords;
    }
}
