package msc.pizza4you.gui.panels;

import javax.swing.JPanel;
import msc.pizza4you.data.PizzaConfiguration;
import msc.pizza4you.data.ToppingDetails;
import msc.pizza4you.core.Engine;
import msc.pizza4you.core.NLPEngine;

/**
 *
 * @author Keshan De Silva
 */
public class ToppingsSelectionPanel extends AbstractPanel
{

    public ToppingsSelectionPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelMain = new javax.swing.JPanel();
        lblMainString = new javax.swing.JLabel();
        txtToppingText = new javax.swing.JTextField();
        panelKeywords = new javax.swing.JPanel();

        panelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Topping Selection", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblMainString.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMainString.setText("I would like to have some :");

        txtToppingText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtToppingText.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtToppingTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblMainString)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtToppingText, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainString)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtToppingText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKeywords.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toppings Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelKeywords.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtToppingTextKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtToppingTextKeyReleased
    {//GEN-HEADEREND:event_txtToppingTextKeyReleased
        updateKeywords();
    }//GEN-LAST:event_txtToppingTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMainString;
    private javax.swing.JPanel panelKeywords;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtToppingText;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getPanelTitle()
    {
        return "Topping Selection";
    }
    
    @Override
    public PizzaConfiguration updatePizzaConfigurations()
    {
        Engine engine = Engine.getInstance();
        PizzaConfiguration pizzaConfiguration = engine.getPizzaConfiguration();
        ToppingDetails toppingDetails = new ToppingDetails();
        
        if (!txtToppingText.getText().trim().isEmpty())
        {
            NLPEngine.getInstance().updateToppingDetails(toppingDetails, txtToppingText.getText());
        }
        
        pizzaConfiguration.setToppingDetails(toppingDetails);
        return pizzaConfiguration;
    }
    
    @Override
    public JPanel getKeywordPanel()
    {
        return panelKeywords;
    }
}
